# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumberjack
  labels:
    app: lumberjack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumberjack
  template:
    metadata:
      name: lumberjack
      labels:
        app: lumberjack
    spec:
      containers:
        - name: lumberjack
          image: tazamaorg/lumberjack:4.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_EXTRA_CA_CERTS
              value: /usr/share/lumberjack/config/certs/ca.crt
          imagePullPolicy: IfNotPresent
        # - name: rule-000-sidecar-rel-1-0-0
        #   image: example.io/sidecar-rel-1-0-0:1.0.0
        #   ports:
        #     - name: http
        #       protocol: TCP
        #       containerPort: 5000
        #   resources: {}
        #   imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: frmpullsecret
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
