apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/typology-processor
namespace: tazama
commonLabels:
  env: tazama
patchesStrategicMerge:
  - replica-patch.yaml
