apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/rule-083
namespace: tazama
commonLabels:
  env: tazama
patchesStrategicMerge:
  - replica-patch.yaml
        value: {name: RULE_VERSION, value: 4.0.0}
        value: {name: RULE_NAME, value: 083}
        value: {name: SUPPRESS_ALERTS, value: true}
        value: {name: SIDECAR_HOST, value: event-sidecar.tazama.svc.cluster.local:5000}
        value: {name: APM_SERVICE_NAME, value: rule-083}
        value: {name: LOCAL_CACHETTL, value: 300}
        value: {name: LOCAL_CACHE_ENABLED, value: true}
patches:
  - target:
      kind: Deployment
      name: rule-083
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: tazama-app-config
          - secretRef:
              name: tazama-app-secrets
  - target:
      kind: Deployment
      name: rule-083
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: FUNCTION_NAME, value: rule-083-rel-4-0-0}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: RULE_VERSION, value: 4.0.0}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: RULE_NAME, value: 083}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: SUPPRESS_ALERTS, value: true}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: SIDECAR_HOST, value: event-sidecar.tazama.svc.cluster.local:5000}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: APM_SERVICE_NAME, value: rule-083}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: LOCAL_CACHETTL, value: 300}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: LOCAL_CACHE_ENABLED, value: true}
