apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/admin-service
namespace: tazama
commonLabels:
  env: tazama
patchesStrategicMerge:
  - replica-patch.yaml
patches:
  - target:
      kind: Deployment
      name: admin-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: tazama-app-config
          - secretRef:
              name: tazama-app-secrets
  - target:
      kind: Deployment
      name: admin-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: FUNCTION_NAME
          value: admin-service
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APM_SERVICE_NAME
          value: admin-service
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SIDECAR_HOST
          value: event-sidecar.tazama.svc.cluster.local:5000
