apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rule-027-staging
  namespace: argocd
spec:
  project: tazama
  source:
    repoURL: 'https://github.com/AbliPayTech/tazama-v4-ci-fork'
    targetRevision: dev
    path: k8s/overlays/staging/rule-027
    # Since kustomize is inferred by path ending in kustomization, no explicit kustomize block needed
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tazama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
