apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/rule-028
namespace: tazama
commonLabels:
  env: tazama
patchesStrategicMerge:
  - replica-patch.yaml
patches:
  - path: ../config/env-patch.yaml
    target:
      kind: Deployment
      name: rule-028
