apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/rule-017
namespace: tazama
commonLabels:
  env: tazama
patchesStrategicMerge:
  - replica-patch.yaml
patches:
  - target:
      kind: Deployment
      name: rule-017
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: tazama-app-config
          - secretRef:
              name: tazama-app-secrets
